### ISSUE TITLE
Change agenda span from day to week or month is too slow.

### ISSUE THREAD

**Issue by cstsunfu** [dhruvasagar/vim-dotoo#103]
Hi, I am very glad to see that you have recently spent time on this plugin, thanks for your awesome job.

I want to know the reason while this plugin changed the agenda view span from day to week will spend so long time.

**Comment by dhruvasagar** [comment]
@cstsunfu Probably the implementation is slow, I have noticed it. There's been an update to the logic, that checks for repeatable dates if they are applicable for the given date. I'll try to optimise this.

**Comment by Gavinok** [comment]
Speaking of it being slow(I kinda get that vim is far from fast) is there a way to set it to default to a month view?

**Comment by dhruvasagar** [comment]
@Gavinok now you can ^

**Comment by Gavinok** [comment]
Thanks man you are the bust!
