### ISSUE TITLE
If using a non-standard refile path, headlines don't show up under refile menu

### ISSUE THREAD

**Issue by ourigen** [dhruvasagar/vim-dotoo#105]
For example, say I have `let g:dotoo#agenda#files=['~/documents/notes/org/*.org']`, 
`let g:dotoo#capture#refile=expand('~/documents/notes/org/inbox.org')`, and in my `inbox.org` 

```
* TODO Some task 
SCHEDULED: <2021-03-23 Tue 20:00>
* TODO Some other task
DEADLINE: <2021-03-24 Wed 20:00>
* Some note :NOTE: 
```
If I hit `gAr` to go to the refile menu, I get
```
Refiles
   No REFILES!
```

I think the refile menu briefly worked for my non-standard `dotoo#capture#refile` after commit a35f144c658ae902b29540e97d6c8bb31387cfbe.

**Comment by dhruvasagar** [comment]
@ourigen Thanks for reporting, this should now be fixed.
