### ISSUE TITLE
Refile sometimes written in wrong file for todos

### ISSUE THREAD

**Issue by kristijanhusak** [dhruvasagar/vim-dotoo#107]
Hi,

I noticed that sometimes my refile file that I configured doesn't get updated when I add a todo, but instead it creates refile file in cwd. This is my configuration:

```vim
let g:dotoo#agenda#files = ['~/Dropbox/notes/**/*.dotoo']
let g:dotoo#capture#refile = expand('~/Dropbox/notes/refile.dotoo')
```

Steps to reproduce:
1. Open vim (in my case neovim)
2. press `gC`, select `todo`
3. add some content for todo
4. write, close buffer
5. Check refile file

Here's the gif showing it. Seems like it happens only for todo, but I tried only note beside todo.

![doto-refile](https://user-images.githubusercontent.com/1782860/113450390-1a794c80-9400-11eb-8241-9832f70a8afb.gif)

System information:

* Vim version: Neovim latest master (v0.5)
* OS: Manjaro Linux

**Comment by dhruvasagar** [comment]
@kristijanhusak i'll close this in favor of #106
