### ISSUE TITLE
Headlines with priority can't be edited from agenda view

### ISSUE THREAD

**Issue by ourigen** [dhruvasagar/vim-dotoo#108]
If I have a task with a priority, like so

```
* TODO [#A] Important task to do
```

and press `<CR>` on it from the agenda view (`gA`), then (Neo)Vim just instead echo `:call dotoo#agenda#goto_headline('edit')` and will not open the file containing the headline for editing.

I'm currently using Neovim v0.50 Nightly, but I also encountered this problem on Neovim v0.44

**Comment by dhruvasagar** [comment]
@ourigen Thanks, i'll take a look
