### ISSUE TITLE
show date/time with notes

### ISSUE THREAD

**Issue by hvanderson** [dhruvasagar/vim-dotoo#11]
@dhruvasagar , this plugin is BOSS. I cannot thank you enough. What is your recommendation for showing the date/time with notes?

**Comment by dhruvasagar** [comment]
Hey, thanks for trying it out!

As of now, the plugin recognises dates from either `DEADLINE` or `SCHEDULED` for a headline. They're also used for displaying these in the `agenda` view. Notes as just basically headlines with a tag ':NOTE:` so if you wanted to see dates you should add a `DEADLINE` or `SCHEDULED` date to it. However I don't think those dates will get added to the `notes` view just the `agenda` view. You could however use the filter feature in the agenda views using `/` to filter just notes there.

So far dates are chosen to represent a time when you need to take action so notes aren't designed to be such.

But if you could care to explain your workflow or why you need time with notes then I could add that.

**Comment by dhruvasagar** [comment]
Hi,

I will close this issue for now hoping I was able to solve your issue. Kindly feel free to reopen this and provide more information if you still need help with this.
