### ISSUE TITLE
gA menu not visible in neovim 0.5

### ISSUE THREAD

**Issue by Gavinok** [dhruvasagar/vim-dotoo#113]
Not sure if this is really considered a bug since it should eventually be fixed but I found that in the current version of neovim's 0.5 beta the menu for `gA` does not seem to show. 

This is probably a bug for the neovim devs to handle rather than for vim-dotoo but I think it would be worth moving to the built in `confirm()` function instead of doing a custom solution.

I started on a pr for this but have not had a chance to work on it for some time. Let me know what you think.

**Comment by dhruvasagar** [comment]
@Gavinok Thanks for reporting this, i'll take another look at switching to confirm

**Comment by dhruvasagar** [comment]
@Gavinok Can you share the neovim version in detail ? I tried on the 0.5 nightly bin from aur and it seems to work

**Comment by Gavinok** [comment]
My mistake I found the source of the error to actually be on my end. Thanks for mentioning that. Seems to be caused my vim-troff plugin some how.

**Comment by dhruvasagar** [comment]
@Gavinok no issues, closing for now. The
