### ISSUE TITLE
Code block highlights

### ISSUE THREAD

**Issue by kristijanhusak** [dhruvasagar/vim-dotoo#115]
Today I was writing some code blocks and noticed they are highlighted as string. I checked the code and saw a dependency on external plugin https://github.com/dhruvasagar/vim-dotoo/blob/master/syntax/dotoo.vim#L293. Also, only few of the filetypes are hardcoded.

I would like to improve on this:
* Parse the `#BEGIN_SRC filetype` with parser, have a reference to it on each dotoo
* Write out a custom function for loading syntax for that filetype, to avoid a dependency on external plugin (seems simple, maybe 15 LOC)
* Call the function that loads them from dotoo syntax file
* Cache things to avoid loading more than once (not sure if this is issue at all)

That way we will load things only when needed, and it should work for all available filetypes in vim.

**Comment by dhruvasagar** [comment]
@kristijanhusak Actually with the help of `:syn-include` it is possible to add support for this without modifying the parser. I haven't spent any time improving the syntax definitions which were largely borrowed from vim-orgmode, but they can be improved.

**Comment by kristijanhusak** [comment]
Yeah, [SyntaxRange plugin](https://github.com/vim-scripts/SyntaxRange/blob/master/autoload/SyntaxRange.vim#L94) uses the `syn-include`, and I want to do the same.
I need the parser to figure out which syntaxes to include. I don't think it's a good idea to load some static list of filetypes, especially if it's a large one.
Or is there a way to somehow figure out the filetype for `BEGIN_SRC` and load the syntax with syn include without parsing or reading the file?

**Comment by dhruvasagar** [comment]
@kristijanhusak The simpler approach would be to go the route of how tpope did for markdown code fences. Basically, with the help of a global configuration such as `g:dotoo_begin_src_languages` we can let the user decide which syntaxes they'd like to support and enable only those.

It would be more optimal to figure out the right syntax to include based on the parser, and I think in the long run we should go in that direction, however the simpler approach should be ok for the time being.

**Comment by kristijanhusak** [comment]
Yeah that also works. I'll set up a PR with a solution very similar to Tpope's.

**Comment by kristijanhusak** [comment]
I just figured out this is a duplicate of #65. Closing.
