### ISSUE TITLE
Error when entering a url in capture mode

### ISSUE THREAD

**Issue by ivanddm** [dhruvasagar/vim-dotoo#125]
Hi, and thanks for a great plugin.

I'm getting this error when entering a url in the first like of a TODO using capture:

![image](https://user-images.githubusercontent.com/20104703/119192061-2b515080-ba88-11eb-99ef-5660307297bb.png)

I wonder if this is by design or it is actually a bug. Normally I like to enter my TODOs in only one line. If I enter the url in the second line instead, there is no issue at all.

Thanks in advance

**Comment by dhruvasagar** [comment]
@ivanddm This is a bug, I have come across this before, the problem is with the precense of `:` character which is used to parse tags, the parser needs a fix, i'll take a look. Thanks.

**Comment by dhruvasagar** [comment]
@ivanddm As a temporary work around, kindly place urls in the body of the headline instead of within the title.
