### ISSUE TITLE
E33: No previous substitute regular expression | :r refresh + Refile view

### ISSUE THREAD

**Issue by talmobi** [dhruvasagar/vim-dotoo#126]
Hello,

I get this error sometimes when I try to refresh or enter the Refile view (gA -> r).

I just created a new task in the refile file with gC, and then I try and enter the gAr refile view and get this error. The agenda view also doesn't show new task that was created.

Trying to enter Refile view (gAr)
![](https://i.imgur.com/z9ZUr2R.png)

Trying to refresh after entering the refile view (r)
![](https://i.imgur.com/MdfiEjQ.png)

**Comment by talmobi** [comment]
Oh I think I may have configured the refile file wrong

I had
`let g:dotoo#capture#refile='~/Dropbox/dotoo-files/refile.dotoo'`

Now that I changed it to
`let g:dotoo#capture#refile=expand('~/Dropbox/dotoo-files/refile.dotoo')`

it seems to work fine

**Comment by dhruvasagar** [comment]
Thanks! I am going to close this issue in favor of you solving your own problem!
