### ISSUE TITLE
[QUESTION] Quick way to return to Agenda view after entering a refile file? (from the agenda view)

### ISSUE THREAD

**Issue by talmobi** [dhruvasagar/vim-dotoo#128]
So when the Agenda view is open, you can press <Enter> to go into that task inside the dotoo buffer. After you are done, is there a way to quickly go back to the Agenda view again?

So far the best way I see is to just quit the buffer and press gA again to open the agenda view. The usual vim suspects does not work (like b# or the goto previous buffer key bind)

Is there a way? Or is is the idea to just use C-T, C-V or C-S to open the dotoo file in a new tab/split?

This is not a feature request implementation, just a casual question 🙏

**Comment by dhruvasagar** [comment]
@talmobi I don't believe there is a way right now, I could set it up so that `<C-^>` can work.

Haven't considered this before and typically I use one of the alternatives (`<Tab>` being my go to) when I want to get back to the agenda view after some quick work in the file.

**Comment by dhruvasagar** [comment]
Also, you can trigger the agenda mapping (`gA`) to go the agenda view again. It is designed to remember things like filters, etc.
