### ISSUE TITLE
Agenda Commands

### ISSUE THREAD

**Issue by frrobert2** [dhruvasagar/vim-dotoo#129]
I downloaded vim-dotoo and I am slowly getting things to work but I am still having and issue in Agenda View.
I can not get any of the following to work.

<CR>: Open headline under cursor & close agenda
<C-S>: Open headline under cursor in split
<C-T>: Open headline under cursor in tab
<C-V>: Open headline under cursor in vsplit
<Tab>: same as <C-V>

Every other command seems to be working.

Reading through I made sure hidden is on
and 
let g:dotoo#capture#refile = ['/home/frrobert/Documents/dotoo-files/refile.dotoo'] 
let g:dotoo#agenda#files = ['/home/frrobert/Documents/dotoo-files/*.dotoo']

are valid and working
I also turned off my other plugins in case that was an issue
I am sure it is something I am not doing correctly.

Thanks for any help you can provide.

**Comment by dhruvasagar** [comment]
@frrobert2 I am assuming you meant that when you use the mappings as documented for the agenda view, they aren't working. Do you get an error ? Kindly also share your vim version output.

**Comment by dhruvasagar** [comment]
Can you also share the output of executing `:verb map <CR>` on the agenda buffer ?
I will try to test this on nvim, since I don't actively use nvim there's a possibility we broke something specifically on nvim.

**Comment by frrobert2** [comment]
I tried vim also and the same issue.

Results 
n  <CR>         @:<C-U>call dotoo#agenda#goto_headline('edit')<CR>                                                                                                                                                 
        Last set from ~/.vim/pack/frrobert/opt/vim-dotoo/ftplugin/dotooagenda.vim line 35

Thanks for your help

**Comment by dengcqw** [comment]
use noremap to define command

**Comment by dhruvasagar** [comment]
@frrobert2 Is this still an issue ? @dengcqw what's the context ?
