### ISSUE TITLE
Compatibility with NeoVIM

### ISSUE THREAD

**Issue by dhruvasagar** [dhruvasagar/vim-dotoo#13]
From a quick run it looks like it breaks with NeoVIM, need to debug the parser and see what may be causing this issue. Needs to be taken up at high priority to try and ensure that it works in both vim & neovim.

**Comment by paretje** [comment]
Well, until now I've encountered one issue, the wrong value for today, which is caused by [this bug](https://github.com/neovim/neovim/issues/3685). I quickly fixed this [here](https://github.com/paretje/vim-dotoo/commit/593cbc59e39fe31229ff2f0c49980275787233dd).

It made me wondering however about the reason to use reltime in the first place?

**Comment by dhruvasagar** [comment]
Well that part is actually borrowed from another library, though I believe it's just more accurate than `localtime()`

**Comment by dhruvasagar** [comment]
I actually don't mind using `localtime()` instead as long as it works, never tried. Also my debugging never reached this part, It was clear the problems were in parsing but wasn't entirely clear where. Thanks for looking into this, perhaps this can be closed with that fix then ?

**Comment by paretje** [comment]
Unless there are other issues. I've been using it a couple of ours now, but this solves the most obvious problem. If we simply use localtime, I guess the code to parse milliseconds can be removed as well. I believe us will always end up being an empty string anyway (which will be converted to zero).
```viml
  let us  = matchstr(ts, '\.\zs.\{0,6\}') " miliseconds
  let us .= repeat(0, 6 - strlen(us)) " zeros to add to get a 6 number digit, needed to be able to rescale to miliseconds
  let us  = matchstr(us, '[1-9].*') " doesn't match
```

**Comment by dhruvasagar** [comment]
Yes we can indeed, I don't see that to be especially valuable in our context.
