### ISSUE TITLE
<C-c><C-c> no longer recalculates delta time in dotoo file

### ISSUE THREAD

**Issue by talmobi** [dhruvasagar/vim-dotoo#130]
Sometimes I change the dates/timestamps for clocking in/out in order to adjust when work has actually started/stopped (when I forget to clock in and out for example) -- usually this would re-calculate the elapsed time, but after updating it no longer does this -- it just stays the same.

Ideas?

**Comment by dhruvasagar** [comment]
It should work when your not on top of any of the two timestamps. When you're on the timestamps, `\<C-C>\<C-C>` tries to normalise (or fix) the timestamp

**Comment by talmobi** [comment]
Hmm no changes should have been done for some time so it should be working as intended as before -- I'm not sure why it has stopped working suddenly.

@dhruvasagar therefore, it is most likely an issue on my end -- I did recently update to OSX 11.5.2 not sure if relevant, though.

It jumps to the closest timestamp and basically changes nothing (but vim still reports as something has been modified I'm not sure why):

demo here where I'm kind of spamming it with and without the buffer being saved in-between.

using version v0.13.1 according to the README and git log

video demo: https://youtu.be/sIegYcHhjJc

**Comment by dhruvasagar** [comment]
@talmobi I see you closed the issue, I hope you understood what's going on. Hitting the key binding anywhere on the line other than on the individual timestamps should produce the result you're expecting.

**Comment by talmobi** [comment]
@dhruvasagar Yes It has worked earlier but now it no longer does work -- I think it's probably an issue with something else I have running or configured. No matter where I am on the line, the key bind jumps to the nearest timestamp and attempts to fix it. Usually I would just go to the beginning of the line, hit the key bind, and then it would add the correct elapsed time -- but no changes have been made in the plugin so it has to be an issue somewhere on my side.

**Comment by dhruvasagar** [comment]
In that case I will reopen and investigate if this is an issue with the plugin

**Comment by talmobi** [comment]
@dhruvasagar Not sure if related but often when clocking in/out inside the refile file (using key bind gI and gO) I get an error -- the error doesn't seem to matter as it properly clocks in/out, but I did not used to get this error.

![](https://i.imgur.com/bRMfy82.png)
