### ISSUE TITLE
Merging syntax highlighting from org.vim plugin

### ISSUE THREAD

**Issue by saccarosium** [dhruvasagar/vim-dotoo#132]
Hi,
I really like the plugin's functionality, but I find that the syntax highlighting is a bit janky, especially on headings, where highlights only one start even in level 2 or 3 headings. I found this plugin [org.vim](https://github.com/axvr/org.vim), and I think borrowing some syntax highlighting bits will be beneficial. I can make a PR with an initial draft but, since I'm not very good with VimL, I need help with the implementation.

Is something you think is worth spending time on?

**Comment by dhruvasagar** [comment]
I have been meaning to rewrite the syntax highlighting so I definitely think that is worth spending time on.
It might be worth looking into utilizing tree-sitter

**Comment by saccarosium** [comment]
> It might be worth looking into utilizing tree-sitter

Yeah, I think it is a good idea! The only problem is the plugin will become neovim only.

I think that you are already aware of this, there is a tree-sitter [parser for orgmode](https://github.com/milisims/tree-sitter-org) that is used in [Orgmode.nvim](https://github.com/nvim-orgmode/orgmode#thanks-to) plugin.
