### ISSUE TITLE
Space between todos

### ISSUE THREAD

**Issue by demiceOP** [dhruvasagar/vim-dotoo#136]
how do I remove those newlines between the todos
![Screenshot_2022-09-29-12-02-43-47_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/99286483/192956655-aed6a2b4-3f79-499a-8f08-c3706a10f1c4.jpg)

**Comment by dhruvasagar** [comment]
@demiceOP What device are you running this on ? Looks like some issue because of resolution / space constraints

**Comment by demiceOP** [comment]
> @demiceOP What device are you running this on ? Looks like some issue because of resolution / space constraints

I'm running this on termux in an android phone

**Comment by dhruvasagar** [comment]
@demiceOP I will try to see if I can add support for a more compact mode for lower resolution devices. This wasn't originally designed for such a use case.

**Comment by demiceOP** [comment]
> @demiceOP I will try to see if I can add support for a more compact mode for lower resolution devices. This wasn't originally designed for such a use case.

Any updates?

**Comment by dhruvasagar** [comment]
@demiceOP Unfortunately no updates as of yet
