### ISSUE TITLE
Trailing whitespaces after dates remove tasks from agenda view

### ISSUE THREAD

**Issue by redst4r** [dhruvasagar/vim-dotoo#137]
Hi,

I noticed that trailing spaces in the `DEADLINE:` and `SCHEDULE:` dates cause the task to NOT show up in the agenda view and will be missed!
Actually any character behind the date specification, e.g. `[2022-10-08]x` causes the task not to show.

Trailing characters are easy to spot (I'd still prefer some syntax errror/warning), but whitespaces are easy to miss (depending on the vim settings, r.h. I dont highlight whitespaces or have trailing spaces removed upon save).

```
* TODO task without trailing whitespace
DEADLINE: [2022-10-15 Sat]
* TODO task WITH trailing whitespace
DEADLINE: [2022-10-15 Sat] 
* TODO task WITH trailing char
DEADLINE: [2022-10-15 Sat]a
```
leads to this agenda view:
```
Span: day
Saturday 15 October 2022
     refile:             Deadline: TODO task without trailing whitespace           
```

I'd consider this a big issue, since it's easy to miss some of this "malformating" and makes the whole thing unreliable (i.e. a simple mishap in editing the dotoos might lead you to miss some important task).

It's probably an easy fix in the file parse, I just don't have any experience in vimscript!

**Comment by dhruvasagar** [comment]
@redst4r Thanks for reporting this, I will certainly take a look.

**Comment by redst4r** [comment]
might be something specific to Nvim 0.8.0, I just upgraded from 0.7 before starting to use dotoo.vim
here's the specifics:
```
> nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

**Comment by dhruvasagar** [comment]
@redst4r I have pushed a fix that ignores trailing whitespace, kindly try it out and let me know if it works as expected.
