### ISSUE TITLE
Refile does not work

### ISSUE THREAD

**Issue by proedie** [dhruvasagar/vim-dotoo#139]
Hi.

I am just testing out this plugin and I can't seem to get refile to work. The files are set-up in `~/.vim/plugin_settings/dotoo.vim` as:

```
let g:dotoo#agenda#files=['~/Notes/Tasks/*.dotoo']
let g:dotoo#capture#refile=expand('~/Notes/Tasks/refile.dotoo')
```

But when I create a new task via `gC` nothing shows up in `refile.dotoo` and when I manually edit that file I get ‘No REFILES!‘ with `gAr`.

Cheers!

**Comment by dhruvasagar** [comment]
@proedie I would need more info to know what's wrong. Some basic questions I'd have would be : 
* Are you saving the capture window with a :wq (saving the task)
* Do you see any errors ?
* What version of vim / neovim are you using ?
* Does vim have permissions to write to that file ?
* When you manually add something to the refile file, are you checking `gAr` after saving it ? Can you share the file, perhaps there's something off with the syntax ?

**Comment by tiberiuiurco** [comment]
> @proedie I would need more info to know what's wrong. Some basic questions I'd have would be :
> 
> * Are you saving the capture window with a :wq (saving the task)
> * Do you see any errors ?
> * What version of vim / neovim are you using ?
> * Does vim have permissions to write to that file ?
> * When you manually add something to the refile file, are you checking `gAr` after saving it ? Can you share the file, perhaps there's something off with the syntax ?

I have the same problem.

- The captured todo does get saved to the refile file, but it appears on the agenda instead of the refile view. There are no errors. 
- I am using neovim v0.9.0. 
- I tried manually adding tasks to the refile file, but it has the same effect as the one described above.
- The todo entry in the agenda has the :refile: tag, but it is not present in the refile view (no filters applied).
```
* TODO Some task
DEADLINE: [2023-02-21 Tue 20:54]
:LOGBOOK:
CLOCK: [2023-02-21 Tue 20:54]--[2023-02-21 Tue 20:55] => 00:01
:END:
```

These are the settings that I have in my configs:
```
let g:dotoo#agenda#files = ["~/org/*.dotoo"]
let g:dotoo#capture#refile = "~/org/refile.dotoo"
```

**Comment by dhruvasagar** [comment]
@tiberiuiurco This is expected behavior, agenda view shows todos that are scheduled / due within 30 days. It does show todos from the refile as well.
