### ISSUE TITLE
problem with date

### ISSUE THREAD

**Issue by BimbaLaszlo** [dhruvasagar/vim-dotoo#15]
I just tried the plugin and it looks promising, but handles the dates incorrectly. If i'm entering `:time:` in to the agenda file, it produces `[2015-06-26 P 08:07]` which is good, but hitting `<C-C><C-C>` on it to normalize the date, it converts it to `[1970-01-01 Cs 01:00]`. This is the behaviour for `gI` (clock in) too:
```
* TODO Sample task
```
becomes
```
* NEXT Sample task
:LOGBOOK:
CLOCK: [1970-01-01 Cs 01:00]
:END:
```
I'm using Windows 7 with Hungarian locale if it takes matter.

**Comment by dhruvasagar** [comment]
Hi, actually, the time doesn't look good, it's supposed to have the day something like `[2015-06-26 Fri 08:07]`, will have a look and ask more questions to understand what the 'P' is about.

**Comment by BimbaLaszlo** [comment]
'P' means Friday in my language ("Péntek") - my *locale is Hungraian* as i wrote.

**Comment by dhruvasagar** [comment]
Ahh, then it might just have to do with locale, looks like it isn't able to parse the datetime `<C-c><C-c>` tries to parse the date time and then correct it. I think I could fix it simply by making my regex a bit more relaxed as it expects a 3 sized day name, and here it is just 1 char.

**Comment by dhruvasagar** [comment]
Hi,

Sorry for the loooong delay, I have pushed a change that should fix this now. Kindly have a look and let me know, thanks for your help!
