### ISSUE TITLE
Summertime issues

### ISSUE THREAD

**Issue by paretje** [dhruvasagar/vim-dotoo#34]
For long, I guess since October, I've got this issue with stamps of which the time alters on any action. I finally searched and found how to reproduce this:
```org
* TODO I have issues
  DEADLINE: [2015-09-25 Fri 20:49]
```

If you do any action, for instance `gI` when editing the file, the time will increase with one hour. When you alter the date to 2015-10-25, the end of summertime in Europe, it works as expected. The same applies if you alter the date to 28th of March.

**Comment by dhruvasagar** [comment]
Will look into this.

**Comment by dhruvasagar** [comment]
Looks like this is some timezone specific issue since I am not able to reproduce it on my local. I will try to investigate more.
