### ISSUE TITLE
Can't get it to work, need basic use tutorial

### ISSUE THREAD

**Issue by bbakersmith** [dhruvasagar/vim-dotoo#35]
I can create notes and todos in the `gC` view, they show up in the refile as specified by `g:dotoo#capture#refile` if I open the file manually, but nothing shows up in any of the `gA` agenda views. I don't know how to proceed.

**Comment by dhruvasagar** [comment]
Do you have `set hidden` enabled ?

**Comment by bbakersmith** [comment]
yes

**Comment by dhruvasagar** [comment]
Well, gC, and several other change / modification operations done on the agenda window are done to the files but not saved. You have to save them explicitly. In agenda view you can do that by <kbd>s</kbd>, or you could save the file if you navigate to it. I am guessing you're not doing that.

**Comment by dhruvasagar** [comment]
Were you able to resolve the issue ? Also make sure vim / you have write permissions to the file in the path as per `g:dotoo#capture#refile`

**Comment by bbakersmith** [comment]
I do `gC`, then `n` to add a note, I write my note and `:w` to save and close the note window. Vim reports "~/.dotoo/refile 30L, 753C written", and sure enough if I open ~/.dotoo/refile the note is there.

Then I `gA` to open the agenda view and `n` to select notes, but no notes. I `gA` then `r` to select refiles, and no refiles listed. I hit `s` in all the views I've listed above, to no effect.

~/.dotoo/refile has write permissions, and is being written to. If I close vim and open ~/.dotoo/refile directly with vim or another editor my notes and everything else I've added using `gC` is persisted there. But still nothing shows up in the `gA` menus.

Am I doing something wrong?

**Comment by dhruvasagar** [comment]
No you are doing right, what version of vim are you using ?

PS: vim-dotoo uses a caching mechanism for performance to show the agenda views, so possibly you are looking at stale view, just hitting `r` in the agenda view should refresh it and perhaps you see the note then.

**Comment by bbakersmith** [comment]
`r` doesn't seem to have an effect.

I'm on a mac, could that be an issue? I'm more used to Linux but my company uses macs for development.

Since the file gets written to fine it seems `gC` and the creation end of things are working for me, but the file isn't being found or read properly by the agenda view. Is there a default location for `g:dotoo#capture#refile` I could try?

Sorry for the bother, I just really want to use this tool!

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec  3 2015 15:29:27)
MacOS X (unix) version
Included patches: 1-944
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: /usr/bin/clang   -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib  -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -o vim        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local/Cellar/python/2.7.10_2/Frameworks -framework Python   -lruby.2.0.0 -lobjc -L/Users/bbaker-smith/.rvm/rubies/ruby-2.0.0-p247/lib    
```

**Comment by dhruvasagar** [comment]
Being on a mac is not an issue, I have tested and used this plugin on both linux and mac, and on both vim and neovim. So that's not an issue and the version you're using is also recent enough.

Once you've captured and saved, it goes to the refile file. So whatever was added should be visible in the refile agenda view. i.e. in `gA`+`r`. Like I said, ideally just refreshing the view (hitting `r` when in the view) should show whatever was added to the refile file. It should also be visible when you open the file yourself.

If you are looking for the added notes within the notes view, i.e. `gA`+`n` then it will not be there since you will see only notes within the agenda files there. i.e. from within files as set by `g:dotoo#agenda#files`.

The ideal flow is, once you've captured a refile entry, you move it to an agenda file. Post that it will be available in other agenda views based on what was captured, a todo, note, etc.

**Comment by bbakersmith** [comment]
I gotcha. Yeah, despite the refile being written to, nothing shows up in the refiles menu (`gA` + `r`) and hitting `r` to refresh has no effect. :-/

**Comment by dhruvasagar** [comment]
That is odd. Do you not have any agenda files besides the refile file ? Kindly share your complete vim-dotoo settings. I will try and reproduce the issue and see how I can help you

**Comment by bbakersmith** [comment]
All I have for configuration is the following (should I have more?):

```
let g:dotoo#capture#refile = "~/.dotoo/refile"
```

I'll also try this on my linux machine when I'm home later, if it works there then maybe it'll provide me a starting point for comparing environments.

**Comment by dhruvasagar** [comment]
Ok i'll have a look and get back to you. I'll try checking the scenario without agenda files settings and see if there are edge cases there.

**Comment by maximsch2** [comment]
I can confirm that I'm having the same problem. I'm using NeoVim and don't have any changes default config values of vim-dotoo. 

Moreover, if I add a file to "~/Documents/dotoo-files/" and put some TODOs there, then I'm not getting anything from it in agenda view by default. Opening that file and asking for Agenda does work though. Maybe there is an issue with detecting "*.dotoo" files in that folder?

**Comment by dhruvasagar** [comment]
Are you sure the dotoo files are in the right format ?
Another thing could be that the agenda (if you've had a long running vim session / use vim sessions) could be set to a date in the past. You can just hit `.` in the agenda view and that takes you to 'today'.

**Comment by maximsch2** [comment]
What I found is that replacing here: https://github.com/dhruvasagar/vim-dotoo/blob/master/autoload/dotoo/parser.vim#L7
with just `readfile(a:file)` makes agenda work, but then clocking in or out doesn't work, complaining about not being able to write to the file. 
I think this suggest is that the issue is with this whole winsave/winrestore trick - if the file is loaded already, then it is working, but if it is not, then it doesn't...

**Comment by dhruvasagar** [comment]
That block loads the file, if it's not loaded. winsave/winrestore are just to ensure we can get vim back to exactly what state it was before we opened the file, just so opening the file (split) doesn't cause unintended modifications to the current view

**Comment by dhruvasagar** [comment]
Can you check `:h winsaveview()` ? Let me know what version of vim you are using ?

**Comment by maximsch2** [comment]
`winsaveview` part works (e.g. nothing pops up and the state of my
buffers/windows is unchanged). It's probably the portion between them.

I'm using one of the later neovim builds (it says 0.1.6-dev).

To provide a bit more clarity:
- If I don't have a file with todos open, then nothing happens and my
agenda/todos view are empty.
- If I do have that file open, then I'm given a choice to add it to agenda
view ("Do you wish to add the current file to agenda files?"). If I choose
no, then everything works correctly. If I choose yes, then this file is
processed twice, I get duplicated todo entries and interacting with them
messes everything up.

**Comment by dhruvasagar** [comment]
Ok, I will try to reproduce this with neovim, the only catch that I can think of is using 'noauto' for opening the file in a split may be causing some issues in neovim. I do that just so the file loads fast and doesn't run any autocommands.

**Comment by maximsch2** [comment]
I thought that neovim might be the issue, but bbakersmith is describing the same issue and he is using VIM...

**Comment by maximsch2** [comment]
I've just tried removing 'noauto' there and it didn't help. 

Also, the buffer seems to be getting opened:
```:ls ->
  1 %a   "parser.vim"                   line 1
  2      "~/Documents/dotoo-files/refile.dotoo" line 0
  3 #    "~/Documents/dotoo-files/sep2016.dotoo" line 0
```

**Comment by dhruvasagar** [comment]
Then the other thing to check would be `getbufline` call.

**Comment by maximsch2** [comment]
Although if I do 
`:echom bufloaded('~/Documents/dotoo-files/sep2016.dotoo')` I get `0`. Am I doing it wrong or interpreting output of `:ls` incorrectly? Doing `getbufline` using `echom` results in "Using List as a String" error.

**Comment by dhruvasagar** [comment]
Just use `:echo` instead of `echom`.
For `bufloaded` you will have to additionally use `expand` ,i.e. `bufloaded(expand(...))`.

Since you're getting that error, it implies the file is loading, in which case maybe for some reason the parsing is going for a toss.

**Comment by maximsch2** [comment]
It looks like `getbufline` is just returning an empty list, so it's not parser's fault.

Another way to fix it that seems to work: remove `quit` after `silent exe` in `s:readfile`. It seems like you expect `quit` to keep the buffer loaded somewhere in the background, but neovim decides to dispose of it (or maybe it's something in my config?).

**Comment by dhruvasagar** [comment]
Well, that should happen only if you don't have `set hidden` in your vimrc. Do you not have that ?

**Comment by maximsch2** [comment]
This is it! Having `set hidden` solves the problem and everything works like magic. Should probably mention that in README and complain if it is not set while loading a plugin if it depends on it.

Will read on `set hidden` to figure out why I need that :)

**Comment by dhruvasagar** [comment]
I mentioned that quite high up in this chain, it's also mentioned in the README. I guess I should highlight that more. Glad it works.

**Comment by maximsch2** [comment]
Haha, haven't noticed that in the second comment. Sorry for that! README on github doesn't mention it though. 

What about using `hide` instead of `quit`? If I'm reading documentation correctly, then it should have the same effect that you are expecting regardless of `set hidden`, right?

**Comment by dhruvasagar** [comment]
I actually didn't know about `:hide`, I will use switch to using that. Will reference here when I do. Thanks.

**Comment by dhruvasagar** [comment]
I've address this in the recent commit f133a1e
