### ISSUE TITLE
Color Allocation Problem

### ISSUE THREAD

**Issue by fugokidi** [dhruvasagar/vim-dotoo#38]
Hi, thanks for the plugins. I try dotoo today, I have a little problem, I'm getting the error saying cannot allocate color and and I cannot write refile.dotoo as well. I'm on MacOS and don't have org-mode background. Can I have a little bit of guidance? Thank you. I have embedded the screen shot below.
![screen shot 2016-08-27 at 5 44 19 pm](https://cloud.githubusercontent.com/assets/9945857/18026601/3ca7f58e-6c7f-11e6-9396-8a9d7dbfa61a.png)

**Comment by dhruvasagar** [comment]
Hi, this looks most likely a problem with your terminal, are you sure u have 256 colors ? What's the value of $TERM ?

**Comment by fugokidi** [comment]
Hi, thank you for your reply. I'm using tmux in iTerm2.  The $TERM value is ```screen-256color```. I configured tmux with some color values as well. It is fine. I think I have 256 colors. Any idea?

**Comment by paretje** [comment]
The same happens using gvim. Apparently, iTerm is using [gui colors](https://github.com/neovim/neovim/issues/4946). In general, the syntax colors of the todo keywords need a gui fallback, separated by a comma from the current `cterm` colors.

To prevent these errors, these lines should be altered in the syntax files:
```vim
                  let l:gui_color = l:color
```

It checks check if `l:color` isn't a number instead of presuming it's a color which can be used with both `gui.g` and `cterm.g`.

**Comment by dhruvasagar** [comment]
Actually the colors are defined using the variable `g:dotoo_todo_keyword_faces`, this is the current setting: 

```
call s:SetGlobalOpts('dotoo_todo_keyword_faces', [
      \ ['TODO', [':foreground 160', ':weight bold']],
      \ ['NEXT', [':foreground 27', ':weight bold']],
      \ ['DONE', [':foreground 22', ':weight bold']],
      \ ['WAITING', [':foreground 202', ':weight bold']],
      \ ['HOLD', [':foreground 53', ':weight bold']],
      \ ['CANCELLED', [':foreground 22', ':weight bold']],
      \ ['MEETING', [':foreground 22', ':weight bold']],
      \ ['PHONE', [':foreground 22', ':weight bold']]
      \ ])
```

Perhaps you can change these to something else.

**Comment by paretje** [comment]
I know, but only cterm colors are defined by default. Thus, the default should become, for example, `:foreground 160,#005FFF` in case of the TODO keyword.

But, if only a color number is given, this should not be used a guicolor. That's the reason we get errors. For cterm we can use colors 0-255 (assuming 256 color support) and color names. For gui, we can use "HTML colors" and color names. If it isn't an HTML color, we should check if it's a number before using it as a guicolor.

If we would check this, with the current default colors, there would have been no error. The color of the keyword would just remain black or white.

**Comment by dhruvasagar** [comment]
You can set it to gui colors only. Setting both isn't supported. You could add a conditional to check if you should be using gui colors if more colors are available and only then set these values, otherwise use default / override terminal colors to your choice.

These are pretty standard colors so I am suprised they aren't available for you. If i could reproduce the problem I may try to solve it but it's not something i've been able to reproduce or had issues with before.

**Comment by paretje** [comment]
Yes it is:
```
            if l:k_v[0] == ':foreground'
              let l:gui_color = ''
              let l:found_gui_color = 0
              for l:color in split(l:k_v[1], ',')
                if l:color =~ '^#'
                  let l:found_gui_color = 1
                  let l:res_faces = l:res_faces . ' guifg=' . l:color
                elseif l:color != ''
                  let l:gui_color = l:color
                  let l:res_faces = l:res_faces . ' ctermfg=' . l:color
                endif
              endfor
              if ! l:found_gui_color && l:gui_color != ''
                let l:res_faces = l:res_faces . ' guifg=' . l:gui_color
              endif
```
So, you just give both, separated by a comma. If you give one, the current code assumes it will work with both `guifg` and `ctermfg`, however that's only the case when it's a name. If it's number, it's only supported by `ctermfg`.

To solve this issue, we just need to add gui color's in the default, and stop using a color number with `guifg`.

**Comment by dhruvasagar** [comment]
No this shouldn't be in the plugin, it should be in your configurations. I don't want to account for a problem that most people don't face. If more people report this I would fix it but not for now. For now you can do this in your vimrc and just set `g:dotoo_todo_keyword_faces` conditionally based on whether it's gui (256+colors) or not.

**Comment by paretje** [comment]
It's not a problem I personally face, it's just that I know it also happens with gvim, which I don't use, normally.

But the fact is that it already is in the plugin. You already can give two colors separated by a comma. I don't see how this would hurt users which use regular vim or neovim (except for iTerm apparently) if this is indeed done in the default configuration?

And the errors are just a bug. It's tested if it's a gui color, but never if it's a terminal color, it's just assumed it will work. Which it won't if they are numbers, only if it's a name.

**Comment by dhruvasagar** [comment]
I had assumed that those colors also work in gui, but I suppose that was wrong. I have added gui colors now, they should be the same as the original cterm ones. Let me know if it works.

**Comment by fugokidi** [comment]
Yes, Sir. It works. I don't understand much about what you guys were talking about. I have to say, you people are awesome. Thank you very much. Hell, yeah, I'm going to learn dotoo.

**Comment by dhruvasagar** [comment]
@fugokidi Sure you're welcome, I had initially misunderstood @paretje, and thought he wanted me to change syntax file, something that I have been meaning to refactor but haven't gotten around to. Fortunately this is already supported so I added sane defaults from my end, which you can still override in your vimrc if you'd like.

**Comment by dhruvasagar** [comment]
@paretje ty for your help :).
