### ISSUE TITLE
This plugin work not as expected.

### ISSUE THREAD

**Issue by cstsunfu** [dhruvasagar/vim-dotoo#47]
When I type gCt to create a todo item vim will open a new file at /private/var/folders but not ~/Documents/dotoo-files/... if I understand the document correctly.

This will happen even if I add 'let g:dotoo#agenda#files = ['~/Documents/dotoo-files/*.dotoo']
let g:dotoo#capture#refile = expand('~/Documents/dotoo-files/refile.dotoo')' to the vimrc.

OS: MacOS
vim: Neovim

**Comment by dhruvasagar** [comment]
Hi, yes that is correct, what opens essentially is a temporary file to enter the details of your task. Once you `save` it, it is then added to the refile dotoo file. From there you can move it to somewhere else when desired. ( I am hoping you're aware of the refile workflow ).

For completeness, dotoo also starts a timer when you open / start capturing, this is valuable from the perspective that you can just start a capture to record the time you spent on some activity, such as a phone call or a meeting. Once you save, the headline is saved in the refile file along with the log including the duration of time that was used..

**Comment by dhruvasagar** [comment]
Have you set `g:dotoo#capture#refile` ? By default it is set to `'~/Documents/dotoo-files/refile.dotoo'` in all likelyhood the path / file does not exist so it may be failing to do so.

**Comment by cstsunfu** [comment]
Yes, I have.  Only when I open the refile.dotoo file and then type gAa I can get the TODO list.
![screen shot 2018-12-05 at 9 04 58 pm 2](https://user-images.githubusercontent.com/24812659/49515367-ad0d8d80-f8d1-11e8-8a20-2c9c88177f45.png)

If I type gAt I will get nothing like this:
![screen shot 2018-12-05 at 9 07 40 pm 2](https://user-images.githubusercontent.com/24812659/49515492-fb229100-f8d1-11e8-816c-c522761e3ebe.png)

If I type gAa at other files except  .dotoo  I will get this:
![screen shot 2018-12-05 at 9 08 06 pm 2](https://user-images.githubusercontent.com/24812659/49515569-33c26a80-f8d2-11e8-8355-79313c62ec38.png)


And another question is mentioned before, when I create a new TODO and saved this item, the plugin will not add this to the refile.

**Comment by cstsunfu** [comment]
OK, I fund  https://github.com/dhruvasagar/vim-dotoo/issues/35 mentioned the same issue, and I set hidden everything work but when I reopen neovim then I type gAa/gAt vim will just exit! If I open the refile then type this everything works as expected. I think when I type gAa the refile.dotoo is not opened automatically.

**Comment by dhruvasagar** [comment]
I am glad you worked it out :).
> If it is possible you can combine this plugin with vimwiki and your table-mode then we will get vim-orgmode :-D
That's a future i'd like to be part of :D
