### ISSUE TITLE
Don't change the # register when capturing

### ISSUE THREAD

**Issue by dareenzo** [dhruvasagar/vim-dotoo#48]
When using dotoo to captures, after you're done with capturing the `#` register has the path of the file where your capture went to. 

I think that if the idea of capturing is to quickly capture your thoughts and go back to whatever you're doing (, which that maybe doing `b#`), you should not hit the capture file when doing `b#`.

Thanks

**Comment by dhruvasagar** [comment]
Nice catch, should be able to fix this using `:keepalt`

**Comment by dhruvasagar** [comment]
Although, the capture is opened in a new window, and my general flow is to just `:wq` to close it (to save in refile). So the `#` register change is only for the current buffer, not the previous window. Let me know exactly how you use it ?

**Comment by dareenzo** [comment]
I use just the way it is documented.

1. do `gC`
1. Choose template and write down idea/thought
1. do `wq`
1. do `b#`, and refile / temporary file where I edited the capture comes up.

**Comment by dhruvasagar** [comment]
Ok, thanks for letting me know, will fix this.

**Comment by dhruvasagar** [comment]
Hi, address this issue in 36afd28cb36acc8f20bd1b3ef5d564aa3ffa03a5, let me know if you face any issues.
