### ISSUE TITLE
got an error when i  choose todo capture

### ISSUE THREAD

**Issue by taigacute** [dhruvasagar/vim-dotoo#49]
![1](https://user-images.githubusercontent.com/41671631/59831325-26536600-9374-11e9-90f9-006fe1b5e3b1.png)

**Comment by dhruvasagar** [comment]
This is some strange error probably caused by some attempt to source dotoo runtime files again or something. Restarting vim should fix this.

**Comment by taigacute** [comment]
@dhruvasagar  not fixed.

**Comment by dhruvasagar** [comment]
Can you elaborate more on your flow ? So I can reproduce this properly.

**Comment by taigacute** [comment]
@dhruvasagar  hi ,thanks for your reply . i just add this plugin . and `gC` select todo by  `t`.

**Comment by taigacute** [comment]
hm . it works .dont know why. another question maybe more like feature. can add calendar in agenda view?  emacs has this feature

**Comment by dhruvasagar** [comment]
Will look into that, kindly open a separate issue for that. Thanks.
