### ISSUE TITLE
Mention that files should be .dotoo in README

### ISSUE THREAD

**Issue by unknownbreaker** [dhruvasagar/vim-dotoo#61]
I had to look into the .vim files in order to figure out what file extension I should be using.

Please specify that somewhere toward the top of the README.

Thank you!

**Comment by dhruvasagar** [comment]
@unknownbreaker Interesting, I shall be more verbose about that. Thanks!

**Comment by ptn** [comment]
@dhruvasagar a simple "check out the sample dotoo.dotoo file in this repo" in the readme would go a *long* way, until there's something more extensive. Make sure to make it prominent! :-)

**Comment by dhruvasagar** [comment]
@ptn I agree, I will add that.
I am also in the process of rewriting the parser, I would like to then have a more detailed documentation describing the spec.
