### ISSUE TITLE
Implement syntax highlighting in BEGIN_SRC blocks

### ISSUE THREAD

**Issue by ptn** [dhruvasagar/vim-dotoo#65]
This would be killer. Any plans? Maybe you could drop inspiration from how vim-notes does it: https://github.com/xolox/vim-notes/blob/master/autoload/xolox/notes.vim#L1163

**Comment by dhruvasagar** [comment]
I haven't planned for this, especially because I wasn't too sure if this is something that I want. However, now, my long term plan for vim-dotoo is for compatibility with org-mode and so I shall work on this.
