### ISSUE TITLE
Captured TODO items go into unexpected refile location

### ISSUE THREAD

**Issue by kadadot216** [dhruvasagar/vim-dotoo#68]
Hello,

I'm trying to configure your plugin and I have made a MWE to test it.
It's working however I have QoL issue concerning ONLY the TODO items.

The biggest issue is that when I capture a todo item first, it is saved into a `~/refile` file instead of the desired refile location I put in my config.
The other types of entries are OK though, they are directly saved into the correct path.

The only workaround I have found is that I have to add any other type of entry (that isn't a todo) first, then all the TODOs added are written in the correct refile path. If I don't do this step all my TODOs will be written to `~/refile` until I add a non-TODO entry.

### How to reproduce:
1) Open nvim
2) Capture a TODO entry (`gCt`)
3) Open the refile view to see if it's there (`gAr`)

**Expected results:**
The TODO entry is visible in the refile view.
The TODO entry is present in the file defined by `g:dotoo#capture#refile`.

**Actual results:**
The TODO entry is absent in the refile view.
The TODO entry is instead present in the `~/refile` file.

**Workaround:**
1) Open nvim.
2) Capture ANY entry that isn't a TODO to correctly trigger the `g:dotoo#capture#refile`. (`gC[phmn]`)
3) Capture a TODO entry.
4) Open the refile view to see if it's there `gAr`.

**Results:**
The TODO item is present along with the garbage entry.

**I have uploaded the steps [in an 5 minute asciicast](https://asciinema.org/a/wnebI6i4ABi3c0v9nTo98uGaw)**.

I'm using **NVIM v0.3.8** and I even tested it on  **NVIM v0.4.3** on **Fedora 31 x64**.
Got the same results on both nvim versions.

My MWE config:

```
call plug#begin('~/.vim/plugged')

Plug 'dhruvasagar/vim-dotoo'

call plug#end()

set hidden

let g:dotoo#agenda#files = ['~/dotoo/*.dotoo']
let g:dotoo#capture#refile = expand('~/dotoo/refile.dotoo')
let g:dotoo#capture#clock = 0
```

**Comment by kadadot216** [comment]
### Update:

The workaround I use in the meantime is to clone the TODO template and remove the `'target '` attribute.

```
let g:dotoo#capture#templates = {
\   'T': {
\       'description': 'Todo clone',
\       'lines': [
\           '* TODO %?',
\     		'DEADLINE: [%(strftime(g:dotoo#time#datetime_format))]'
\   	]
\   }
\}
```

**Comment by dhruvasagar** [comment]
@kadadot216 Thanks for filing this issue. In recent past I did face some issues with the capturing target changes. Are you sure you've tested this with the latest changes ? I haven't tested the plugin extensively with NeoVIM, however i'll take a look at this and share what I find.

**Comment by kadadot216** [comment]
I have installed it yesterday through vim-plug so I think it's the latest commit.

**Comment by hasansujon786** [comment]
Any update on this issue.

**Comment by dhruvasagar** [comment]
@hasansujon786 I actually figured out the cause of the issue, will push a fix soon.

**Comment by stuart-warren** [comment]
I'm still hitting this, assume a fix hasn't been pushed yet

Thanks

**Comment by stuart-warren** [comment]
I've worked around it by specifying the file extension before any section name:
```vim
let g:dotoo#capture#templates = {
                      \ 't': {
                      \  'target': 'refile.dotoo:Tasks'
                      \ }
                      \}
```

**Comment by dhruvasagar** [comment]
I believe I have understood when this happens, when haven't opened the agenda (which opens the agenda files) yet, if we try to capture and save it, it is unable to find the refile dotoo file and ends up trying to create a new file. i'll push a fix today
