### ISSUE TITLE
Date doesn't decrement inside capture buffer

### ISSUE THREAD

**Issue by kadadot216** [dhruvasagar/vim-dotoo#69]
Hello, this is the lesser of the 2 issues I encountered today while testing your plugin

When I am in the capture buffer and try to decrement the date by pressing `<C-x>` it continues to increment.

The date decrement works as excpected though when editing the local agenda files.

I use **NVIM v0.3.8** on **Fedora 31 x64**

Thank you for this amazing plugin. Good to see Emacs org-agenda ported to vim!

**Comment by dhruvasagar** [comment]
@kadadot216 Never noticed this, thanks for reporting!
