### ISSUE TITLE
Month span view doesn't show tasks due past certain date

### ISSUE THREAD

**Issue by kadadot216** [dhruvasagar/vim-dotoo#71]
This is somewhat a continuation from #70, I noticed that the month span view is showing similar behavior.

First I want to know if it is intended that the month span cover all incoming tasks.

If it is so, 
When I plan a task months in advance, past a certain date, it doesn't appears anymore (in my case June 29th)

**Steps to reproduce:**
Create a task due to June 29th.
Open agenda view and switch to month span.
Edit the date of the task to June 30th.
Refresh the agenda view.

I've made [an asciicast](https://asciinema.org/a/cLSMdrO6nQuApiDbuFsxirysS)

There is no problem when I switch to week's span and fowards the date view to the task's week.

**Comment by dhruvasagar** [comment]
@kadadot216 I believe it should work well now, the issue was that the last day of the month was not inclusive in the range due to a bug.

**Comment by kadadot216** [comment]
Thank you.
