### ISSUE TITLE
Increment/decrement on timestamps for hours/minutes

### ISSUE THREAD

**Issue by belugame** [dhruvasagar/vim-dotoo#74]
> <C-A>: Increment date under cursor by 1 day, can be preceded with a [count]
> <C-X>: Decrement date under cursor by 1 day, can be preceded with a [count]

It works on days, though my use case is that I often forget to clock in/out of something and want to adjust a time log quickly back x minutes or split a bigger one into two. So increasing/decreasing on hours and minutes would be really handy. :)

Thank you for your great work!

**Comment by jmzagorski** [comment]
do `<C-A>` `<C-X>` work for you when under a date in the `CLOCK` or `DEADLINE`?  In my todo view when i am on my either line, hitting either mapping will change the year, and then jump to the last digit in the minute and do nothing

**Comment by belugame** [comment]
@jmzagorski  For me pressing either `<C-A>` or` <C-X>` will increase the `CLOCK` or `DEADLINE` by 1 day

**Comment by dhruvasagar** [comment]
> @jmzagorski For me pressing either `<C-A>` or` <C-X>` will increase the `CLOCK` or `DEADLINE` by 1 day
> 
> That is on a minimal vimrc

That's how it designed to work.

**Comment by dhruvasagar** [comment]
@belugame I have just pushed a change to facilitate this request. I have added a new command `DotooAdjustDate` that allows you to adjust dates by an arbitrary amount. You can read `:h :DotooAdjustDate` for more details on usage.
For your use case, I would recommend defining custom mappings and bind it to `:DotooAdjustDate +1h` and `:DotooAdjustDate -1h` for dotoo & dotoocapture buffers.

**Comment by belugame** [comment]
@dhruvasagar  Thank you so much :) I just tried it out with these mappings for hours and minutes and it works nicely.

```
nnoremap <c-w> :DotooAdjustDate +1h<CR>
nnoremap <c-s> :DotooAdjustDate -1h<CR>
nnoremap <c-e> :DotooAdjustDate +1M<CR>
nnoremap <c-d> :DotooAdjustDate -1M<CR>
```

**Comment by jmzagorski** [comment]
thanks @dhruvasagar. I will try to get more debug information for you and open a new issue. I launched vim with the vimrc_example provided by the install, did `packadd vim-dotoo` and went to the `CLOCK` and it did not increase/decrease by one day.

**Comment by dhruvasagar** [comment]
@jmzagorski Sure let me know, just make sure your cursor is somewhere on the date. It should work.

**Comment by dhruvasagar** [comment]
@belugame The alternate api you could use is `dotoo#adjust_date()`

**Comment by belugame** [comment]
@dhruvasagar  I noticed that the resulting duration does not update when changing the start/end time. Lets say you had a CLOCK with a 5 minute period and add 10 minutes to it, it will still say it was only 5 minutes long. Also with <C-C><C-C> it does not update. Would be great :)

**Comment by dhruvasagar** [comment]
@belugame Kindly open another issue for this
