### ISSUE TITLE
(suggestion/enhancement) Way of sorting items per remaining time in View mode

### ISSUE THREAD

**Issue by kadadot216** [dhruvasagar/vim-dotoo#87]
Hello dhruvasagar, 

When I browse my agenda items, they are sorted by file, this is the default behavior of vim-dotoo, it parse all entries containing a GlobalOpt in the order they were added or edited.

This is a problem when I put agenda items across multiple files because it disorganizes the chronology of my tasks.
My solution for now is putting them all in the same file, but by doing so, I lose the context in which they were created, plus with too much items, I end getting lost.

It would be great if, in addition to the filter command, there were a way of sorting them by manipulating the normal output or any other way, so all agenda entries are correctly sorted per date.

I use files for arranging my entries per context, and it is good for organizing tasks and not getting lost in a too long file.

**Comment by kadadot216** [comment]
Illustrating what I am talking about

Expected:
```
        foo:        2h 9m 57s ago: TODO Task 1                                        
        bar:        2h 9m 57s ago: TODO Task 4                                        
        baz:        2h 9m 57s ago: TODO Task 7                                        
        foo:      In 1d 2h 53m 3s: PROGRESS Task 2                                    
        bar:      In 1d 2h 53m 3s: PROGRESS Task 6                                    
        baz:      In 1d 2h 53m 3s: PROGRESS Task 9                                    
        foo:     In 7d 21h 50m 3s: NEXT Task 3                                        
        bar:     In 7d 21h 50m 3s: NEXT Task 5                                        
        baz:     In 7d 21h 50m 3s: NEXT Task 8                                        
```

Actual result:

![1596047198](https://user-images.githubusercontent.com/49029219/88838647-eb646880-d1ea-11ea-8490-058610ca0590.png)

I have added the `PROGRESS` opt.

**Comment by dhruvasagar** [comment]
The agenda items are actually sorted by time till deadline. The filters were designed to allow for being able to focus on specific agenda items. While I agree it isn't as good as sorting, I find the idea of sorting the agenda by anything other than the deadline a bit awkward. Using filters, you can focus on items of a file, tags or a specific todo state.

**Comment by kadadot216** [comment]
Got it, I will try adapting my worflow around filters from now on.

**Comment by kadadot216** [comment]
I eventually caved in and wrapped my head around the code to implement the desired functionality.
It took me the whole day to understand the way the headlines are parsed, wrapped and displayed.
It works like a charm now.

I could see and appreciate all the hard work you put into this plugin,
I switched from Emacs to Vim 3 years ago, and no any of the dozens of software/app/methods/services that I tried could replace the versatility, the flexibility and the extensibility of org-mode, mostly on vim.

Now it's months that I use dotoo thank you infinitely for that!

![tty](https://user-images.githubusercontent.com/49029219/89102826-c3a91680-d41d-11ea-8cec-626908eed158.gif)

**Comment by dhruvasagar** [comment]
@kadadot216 Thanks for the kind words. I did put in a lot of effort in building this, and my intention was to build an extensible modular plugin. I think I have done a decent job, although the parser is a bit lacking in depth and makes it difficult to add features to the spec.
Do share your opinions on things that can be improved, including documentation.

**Comment by kadadot216** [comment]
Hello, I am uploading the patch of the modifications I've made in for you or anyone who is interested.

[vim-dotoo-agenda-view.patch.txt](https://github.com/dhruvasagar/vim-dotoo/files/5209545/vim-dotoo-agenda-view.patch.txt)

**Comment by dhruvasagar** [comment]
@kadadot216 would be nice to see it in action. Also, I am open to a PR with this added as an optional sorting strategy controlled by some configuration.

**Comment by kadadot216** [comment]
You can already see it in action in the gif I've previously posted. It is possible to work on a pull request.

As you see, I propagated the `diff` method upwards to be usable directly with the headlines objects with `metadata_methods.diff` and `headline_methods.diff`.

I've also added the `dotoo#agenda#headlines_preproc` function that acts as a preprocessing filter and is called from each of the agenda display (`build_agendas`) AND cursor selector functions (`dotoo#agenda#goto_headline`, `dotoo#agenda#start_headline_clock`, `dotoo#agenda#stop_headline_clock`, `dotoo#agenda#change_headline_todo`).

From that, I could set a parametization function that could be changed as a plugin variable in the user's .vimrc
