### ISSUE TITLE
Clocking out after changing a caption changes it back

### ISSUE THREAD

**Issue by belugame** [dhruvasagar/vim-dotoo#88]
- clock in on a caption like "* Foo"
- change caption to "*Foo bar"
- clock out
-> Caption changes back to "* Foo"

**Comment by dhruvasagar** [comment]
Fascinating, this is because of the aggressive caching by the parser. Will investigate.

**Comment by dhruvasagar** [comment]
@belugame If you saved the file after changing the caption and then proceed to clock out, it should behave as expected. I think that's acceptable for now.
