### ISSUE TITLE
agenda view has displays issues after operations using buffer prompts, when having more than the defaults dotoo states 

### ISSUE THREAD

**Issue by kadadot216** [dhruvasagar/vim-dotoo#90]
In my first example, I have my extra opts, for a total of 16. When I manipulate my elements, my agenda view is bonked after the todo state prompt because it is too big, this results as having my cursor to move down from the headline I changed the todo state, as follows:

![ex1](https://user-images.githubusercontent.com/49029219/89101834-bdfb0300-d414-11ea-82c0-3dce0961a5a8.gif)

Plus, it puts bits of the "Select todo state" message, that is supposed to be at the end, on top of the prompt buffer.

In the second gif, this is the normal use case, with the default states.

![tty](https://user-images.githubusercontent.com/49029219/89101835-bfc4c680-d414-11ea-8451-fd51eba0dbd9.gif)

Like the 1st, it puts garbage characters on top of the prompt

In the `dotoo#utils#getchar` function in `autoload/utils.vim:30, the line` 

```viml
  let &cmdheight = len(split(a:prompt, "\n"))
```

seems to affect the display when we add more custom todo states.

What's exactly the point of `cmdheight` and `old_cmdheight`, because if I disable line mentionned above, it solves my issues with my custom states. (in the 3rd gif)

![tty](https://user-images.githubusercontent.com/49029219/89102418-0832b300-d41a-11ea-9f5c-fa8284805e2c.gif)

**Comment by kadadot216** [comment]
I had the issue for a time, since I put my own todo states.
and I retested in from your `origin/master`

How to reproduce:

Add these parameters in your .vimrc to have a lot of todo states to display in the prompt.

```viml
let g:dotoo_todo_keyword_faces = [
\   ['TODO', [':foreground 160,#df0000', ':weight bold']],
\   ['NEXT', [':foreground 27,#005fff', ':weight bold']],
\   ['MAYBE', [':foreground 202,#efa080', ':weight italic']],
\   ['ELAB', [':foreground 202,#f07ef0', ':weight bold']],
\   ['DONE', [':foreground 22,#005f00', ':weight bold']],
\   ['WAITING', [':foreground 202,#ff5f00', ':weight bold']],
\   ['PROGRESS', [':foreground 202,#00ff00', ':weight italic']],
\   ['SOON', [':foreground 202,#eeeeee', ':weight bold']],
\   ['FUTURE', [':foreground 202,#bbbbbb', ':weight italic']],
\   ['HABIT', [':foreground 27,#002bee', ':weight italic']],
\   ['QUESTION', [':foreground 202,#ff5f00', ':weight italic']],
\   ['IDEA', [':foreground 202,#ffd000', ':weight italic']],
\   ['EVENT', [':foreground 202,#00d0b0', ':weight bold']],
\   ['CANCELLED', [':foreground 22,#cf0000', ':weight bold']],
\   ['MEETING', [':foreground 22,#005f00', ':weight bold']],
\   ['PHONE', [':foreground 22,#005f00', ':weight bold']]
\]

let g:dotoo#parser#todo_keywords = [
\   'TODO',
\   'NEXT',
\   'MAYBE',
\   'ELAB',
\   'WAITING',
\   'PROGRESS',
\   'SOON',
\   'FUTURE',
\   'HABIT',
\   'QUESTION'
\   'IDEA',
\   'EVENT',
\   'PHONE',
\   'MEETING',
\   '|',
\   'CANCELLED',
\   'DONE'
\]
```

Then from your agenda view, change the state of a todo.

When you do this to the 1st or the 2nd headline from the top, the cursor is ok, it moves when you change the ones after these.

**Comment by dhruvasagar** [comment]
@kadadot216 I have removed the cmdheight manipulation, it appears it is no longer necessary at least with latest versions of vim. That hack was used because sometimes vim had issues when displaying large prompts.

**Comment by kadadot216** [comment]
Hello, reopening the issue because of having changed the line 

```viml
  if char =~# a:accept | return char | endif
```

in `autoload/dotoo/utils.vim:32` doesn't update the dotoo state in the agenda view.

When putting it back to
```viml
  if char =~? a:accept | return char | endif
```
it removes the issue.

**Comment by dhruvasagar** [comment]
@kadadot216 hope we're good now.
