### ISSUE TITLE
Allow agenda view to display the date of the event?

### ISSUE THREAD

**Issue by etrmrh** [dhruvasagar/vim-dotoo#92]
I'm migrating over from [vim-orgmode](https://github.com/jceb/vim-orgmode) and found that I miss seeing the agenda in a calendar type of view. What I mean is that I would like to be have the option to change the agenda view from

```
in 1d        Task 1
in 1d16h     Task 2
in 3d4h      Task 3
```
to

```
Sat Oct 17 2020
10:00     Task 1
16:00     Task 2

Mon Oct 19 2020
14:00     Task 3
```

I know that this plugin was based on vim-orgmode, so has this feature been purposely changed? Or is there a way to view the agenda like this that I missed?

**Comment by dhruvasagar** [comment]
@etrmrh The main reason we don't have this feature is because I don't use it.

But I do see value in building such a view and shall take a stab at it. We already have an option to change the `span` of the agenda view from per day to per week / month, I think that could make use of this. I have always wanted to improve the week / month span views, I just hadn't needed to.

PS : This plugin isn't based on vim-orgmode, although I did borrow some code from it for syntax highlighting.

**Comment by etrmrh** [comment]
@dhruvasagar I think if you can work this feature in that would make the agenda more useful for more people. Personally I like having a birds-eye view over my tasks and events. With Org-mode agenda, having a timeline of exactly when the event falls help me plan out what to do the days leading up to it. You don't have to overwrite the original view, just allowing the option to change it to that format would be enough for me

Also, my mistake for my comment regarding the plugin being based off of vim-orgmode. I did skim through the codebase a bit more and it is different. For one, the parser you implemented here is way faster than that of vim-orgmode. The latter would lock up my Vim session on larger file, while this I load it in seconds. I think this plugin is almost perfect for my needs, just some minor nitpicks here and there.

**Comment by dhruvasagar** [comment]
@etrmrh Thanks for the encouraging comments. Regarding the timeline thing, the more I think about it, the more it seems to make sense to me. I have always felt the week / month views were rather limited and confusing, I think the above way of representing the timeline does make more sense. I will focus on this in the coming weeks.

**Comment by dhruvasagar** [comment]
@etrmrh I've finally pushed an early version of this, it seems to be working well however I haven't tested for all edge cases ver well. Kindly take a look and let me know what you think.

**Comment by ourigen** [comment]
@dhruvasagar Hey there, hope you don't mind if I chime in. I'm also another user who was looking forward to this change, and am very excited to see this implemented. The few suggestions I have are:

- **Allow hiding dates without events.** If my tasks are spaced out at least a week or so, having 7 extraneous lines with just dates and no valuable information take up screen space that I could use to preview future deadlines
- **Allow the agenda week/month view to look forward.** When I change the agenda view to "week" on Sunday 14 March, I would like to see 7 days onward from the current starting date (from Sunday 14 March to Saturday 20 March.) At the moment, it shows from the beginning of the week (Monday 08 March) to end of the week (Sunday 14 March), which takes up screen space with information I no longer need. However, I understand the use case for the current display, so this isn't as big of a concern for me.
