### ISSUE TITLE
The report of clocking summary is not right aligned for double width characters.

### ISSUE THREAD

**Issue by cstsunfu** [dhruvasagar/vim-dotoo#93]
Maybe you could rewrite the function log_line in autoload/dotoo/agenda_views/plugins/log_summary.vim to fix this issue.

I respect your work.

**Comment by dhruvasagar** [comment]
@cstsunfu Can you share a screenshot please ?

**Comment by cstsunfu** [comment]
@dhruvasagar  Like this:
<img width="766" alt="截屏2020-11-11 上午2 38 48" src="https://user-images.githubusercontent.com/24812659/98717020-77c81f00-23c7-11eb-90af-f74b244cdf51.png">

**Comment by dhruvasagar** [comment]
Thanks, i'll have a look.
