### ISSUE TITLE
Allow alternative mapping for increment date (<c-a>)

### ISSUE THREAD

**Issue by j-hui** [dhruvasagar/vim-dotoo#95]
Similar to #44, but for other keybindings. I usually have `<c-a>` mapped to something else.

**Comment by dhruvasagar** [comment]
@j-hui interesting. The native vim mapping <kbd><C-A></kbd> allows one to increment number under cursor and this follows suit. I will have a look.

**Comment by j-hui** [comment]
For context, I have `<c-a>` remapped to `^` to imitate readline bindings.

**Comment by j-hui** [comment]
Does this binding conflict with tpope/speeddating?

**Comment by dhruvasagar** [comment]
I have provided plug mappings that can now be overriden individualy
