### ISSUE TITLE
The agenda views don't show TODOs when the buffer is closed

### ISSUE THREAD

**Issue by FabioRamatis** [dhruvasagar/vim-dotoo#97]
First, thank you for you amazing plugin!

The video example basically explain well enough what's the issue.
https://asciinema.org/a/cTTA8zNH5y6x6EpGD1XKF6hO0

When I open the todo.dotoo file and bring up agenda view, it shows the TODO properly, but when I just want to open neovim and bring the agenda, it doesn't catch the TODOs.

**Comment by dhruvasagar** [comment]
> First, thank you for you amazing plugin!
You're welcome!
> 
> The video example basically explain well enough what's the issue.
> https://asciinema.org/a/cTTA8zNH5y6x6EpGD1XKF6hO0
> 
> When I open the todo.dotoo file and bring up agenda view, it shows the TODO properly, but when I just want to open neovim and bring the agenda, it doesn't catch the TODOs.
Are you sure your dotoo file is within the path set in `g:dotoo#agenda#files` ?

**Comment by FabioRamatis** [comment]
I can echo out the variable correctly when I start my neovim

    https://asciinema.org/a/2jSCKYpRWpYYaah7Hk8W7u9tH

**Comment by dhruvasagar** [comment]
@FabioRamatis Can you check with latest if this is still an issue ? I believe this shouldn't be an issue anymore, however I recommend enabling vim option `hidden`, however, recently I pushed changes that removes my dependence on it.
