### ISSUE TITLE
@dhruvasagar Hey there, hope you don't mind if I chime in. I'm also another user who was looking forward to this change, and am very excited to see this implemented. The few suggestions I have are:

### ISSUE THREAD

**Issue by dhruvasagar** [dhruvasagar/vim-dotoo#99]
@dhruvasagar Hey there, hope you don't mind if I chime in. I'm also another user who was looking forward to this change, and am very excited to see this implemented. The few suggestions I have are:

- **Allow hiding dates without events.** If my tasks are spaced out at least a week or so, having 7 extraneous lines with just dates and no valuable information take up screen space that I could use to preview future deadlines
- **Allow the agenda week/month view to look forward.** When I change the agenda view to "week" on Sunday 14 March, I would like to see 7 days onward from the current starting date (from Sunday 14 March to Saturday 20 March.) At the moment, it shows from the beginning of the week (Monday 08 March) to end of the week (Sunday 14 March), which takes up screen space with information I no longer need. However, I understand the use case for the current display, so this isn't as big of a concern for me.

_Originally posted by @ourigen in https://github.com/dhruvasagar/vim-dotoo/issues/92#issuecomment-798925370_

**Comment by dhruvasagar** [comment]
@ourigen I have address the first part of your request, kindly refer to the documentation / commit description for details.

Addressing the second part is also easy, I am thinking about any side effects. Will share here once I push something.

**Comment by dhruvasagar** [comment]
@ourigen I have addressed both these requests. Kindly take a look and let me know.

**Comment by ourigen** [comment]
@dhruvasagar Thanks for the quick work on this! From my brief test, both new features seems to be working exactly as I needed

**Comment by dhruvasagar** [comment]
@ourigen That is by design as I understand, for today we try to show all `upcoming` tasks, which includes tasks in the future. There's a separate configuration that controls how far in future we should look. I will still refer to the org mode documentation in this and see if I find any discrepency.

**Comment by dhruvasagar** [comment]
@ourigen perhaps in week / month span modes, this rule shouldn't apply, I will cross check with Org Mode on this and revert.

**Comment by ourigen** [comment]
@dhruvasagar Now that you mention it, I do see the purpose of having tasks also listed under the current date. Honestly if it is easier to leave it as is, I wouldn't mind. The main features I was looking for were already quickly implemented, so thank you for your hard work on this
